[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "A minimal demonstration of an MCP server using Pixi and uv."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "cmcp==0.2.0",
  "mcp[cli]==1.8.0"
]